### ISSUE TITLE
Fix click not working properly on some targets

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#161] opened 2021-02-07 11:16 UTC

**Comment by yvolk** [comment] 2021-02-08 06:10
This is a duplicate of https://github.com/korlibs/korge/issues/772 "Android device: onClick event is about previous click"

As I checked some days ago, the bug is still present.
In addition, generally responsiveness to taps on a touch screen on Android is subpar. I mean even in order to make above reported "wrong clicks" a User should tap much more "accurate" and longer than for any other Android app :-(

On the other hand, swipes work on Android devices instantly and as expected.

**Comment by soywiz** [comment] 2021-02-08 10:06
This task is about the precision of the click in some targets. It uses the native click from the operating system, but sometimes a slight movement prevents the click event from triggering. Right now some people use the up event. The up event might not work properly in some cases for example with "tap clicks" on a touchpad. I have to check.

The android issues are being handled separately. I'm making the multitouch events to work properly and to provide some simple gesture recognizing APIs here: https://github.com/korlibs/korge-next/pull/162

Once the multitouch API works properly and I have been able to validate it will work, I will redirect them to plain mouse events, and that will hopefully fix  the click issue too on Android.

**Comment by yvolk** [comment] 2021-02-08 12:36
@soywiz Thanks for the insights.
Just wanted to correct my above report about Swipe events on Android:
As one of my experienced Android users (an IT guy...) reported, swipes in our KorGe-based app aren't as precise as they are in other Android apps :-( 
I mean that "wrong" direction is sometimes chosen, when a User perceives that the swipe was accurate enough, although not ideally oriented...
I think this is about intelligence of the swipe-direction-detection algorithm...

**Closed** 2021-05-02 01:44 UTC
